### ISSUE TITLE
ImportError: No module named figures.settings.lms_production

### ISSUE THREAD

**Issue by saputro-dwy** [overhangio/tutor-figures#1]
Hi, i want to implement these plugins. but I have a problem when applying the command 
`tutor local init`
namely:  `ImportError: No module named figures.settings.lms_production.`
is there any step that I am lacking.
thanks in advance

**Comment by saputro-dwy** [comment]
I just need run `pip install figures`.
thankyou

**Comment by bvenkatr** [comment]
Hi, I am having the same issue
![image](https://user-images.githubusercontent.com/6078345/80449840-c804f580-893d-11ea-8d58-f0f48665d824.png)

and then I have added **figures** in **$TUTOR_ROOT/env/build/openedx/requirements/private.txt**
![image](https://user-images.githubusercontent.com/6078345/80450466-339b9280-893f-11ea-9051-93e6c07b6d16.png)

and build the openedx image `time tutor images build openedx` and `tutor local quickstart`

It almost took 8 mins, Wouldn't it be good to pre-install as part of `openedx` image build
![image](https://user-images.githubusercontent.com/6078345/80450626-8bd29480-893f-11ea-9443-0109824882ad.png)

**Comment by regisb** [comment]
It appears Appsembler has created stable releases while we were still on 0.3.0-prerelease. The latest figures plugin will point to v0.3.8, which should address your issue.

> It almost took 8 mins, Wouldn't it be good to pre-install as part of openedx image build

@bvenkatr It was a long time ago, but do you remember when it took a couple hours to install Open edX? :stuck_out_tongue: I also wish it would be faster to rebuild the openedx docker image, but this is a complex project. I do not want to bundle figures with the base openedx docker image because I do not want to bloat it further.

**Comment by bvenkatr** [comment]
okay, I got it. Do you have plan to upgrade to v0.3.8 in near future? I will try from my side as well and if it works well then I can generate PR as well.
